### ISSUE TITLE
Include Custom Message in Admin Emails Setting

### ISSUE THREAD

**Issue by alexmustin** [alexmustin/woocustomemails#10]
**Is your feature request related to a problem? Please describe.**
Some users would like the ability to include the Custom Email Messages inside the Admin emails.

**Describe the solution you'd like**
The user should have a Setting to enable the Custom Email Messages to be included in Admin emails.

This could be either a Global setting on the _Custom Emails > Settings_ page, or it could be a meta checkbox when editing each Custom Email Message.

**Describe alternatives you've considered**
N/A - this is a new feature request

**Additional context**
Plugin Support Forum request:
[https://wordpress.org/support/topic/custom-email-stopped-showing-in-admin-order-notifications-last-month/](https://wordpress.org/support/topic/custom-email-stopped-showing-in-admin-order-notifications-last-month/)

**Comment by dunn123** [comment]
my client would like the info in both customer and admin emails too
