### ISSUE TITLE
"Custom Emails" tab not showing for certain types of products

### ISSUE THREAD

**Issue by cantonbecker** [alexmustin/woocustomemails#18]
The popular LearnDash plugin adds a new type of product to Woo products. In addition to being able to select from "Variable" or "Simple" etc, you can select "Course".

When "Course" is selected, the Custom Emails tab disappears.

Expected behavior: Custom Emails tab should persist even when choosing an off-brand product type.

![Screenshot 2020-07-09 12 56 54](https://user-images.githubusercontent.com/4149987/87080140-6b973f80-c1e4-11ea-9d66-c542f267868b.png)
![Screenshot 2020-07-09 12 56 44](https://user-images.githubusercontent.com/4149987/87080143-6cc86c80-c1e4-11ea-838a-13b0da06a810.png)

Temporary fix, I think? I added the class **show_if_course** to $display_classes_default in **woo-custom-emails-per-product.php**

**Comment by alexmustin** [comment]
@cantonbecker - I created a page for users to add that "show_if_xxx" class.

Custom Emails > WCE Settings
![Screen Shot 2020-07-09 at 12 29 22 PM](https://user-images.githubusercontent.com/1307497/87082403-d5f9b100-c1df-11ea-86db-573d140f7b7d.png)

**Comment by alexmustin** [comment]
Please consider that I cannot develop this plugin to work with every possible WooCommerce Custom Post Type that exists. Some of these special products are setup to send emails outside of the way default WooCommerce Product emails are sent, making the process even harder.

The purpose of this plugin is to work with DEFAULT WooCommerce product types... that's it.

If you need to modify this for your own needs, feel free to fork it and go for it!

**Comment by cantonbecker** [comment]
That’s perfect, thanks very much for this extra bit of customizability. That means I won’t have to edit your plugin every time I update it. :)

From your earlier response, I do appreciate that this is a “use at your own risk” type of thing, since there’s no way you can guarantee that every woocommerce product type extension is going to behave as expected when it comes to triggering emails.

And thanks again for this excellent plugin. It’s a desperately needed feature for many woocommerce scenarios. I’ll be a happy paying customer if and when you create a commercial version of this plugin.

**Comment by alexmustin** [comment]
Thanks for the kind words @cantonbecker !
