### ISSUE TITLE
Custom email per product variation

### ISSUE THREAD

**Issue by climbingvan** [alexmustin/woocustomemails#26]
I've seen this has already been requested in the past, so we really hope you consider including it soon! We would find it incredibly useful. We need to be able to add a custom email for each product variation. Thanks!

**Comment by katmaia** [comment]
Hello! I also want to ask if it is possible to create the option of sending custom Email for each product variation?!?! Most of the products of my company are variable, and we can´t send the same message (Zoom link ID) for all the variations, as they are different... Thank you!
