### ISSUE TITLE
Is this still under development ? Bugs and feature requests are not followed ?

### ISSUE THREAD

**Issue by BE-Zizoo** [alexmustin/woocustomemails#33]
I have several bugs described but there is no follow up anymore ?

**Comment by alexmustin** [comment]
To answer your question -- yes I do receive these requests. It is very hard being the only person to update anything, and having a normal full-time schedule, while trying to keep up with update requests for free software.

Please understand I wish I had the free time to only work on this plugin, but as of now I must prioritize paying work first.
